[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests'
cache_path  = 'cache_forge'
evm_version = "shanghai"
optimizer_runs = 200
optimizer = true
solc_version = '0.8.19'

[rpc_endpoints]
berapriv = "${RPC_URL}"

[etherscan]
berapriv = { key = "x", chain = 2061, url = "https://scan-api.berachain-internal.com/api/"}